# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/lintula/worktmp/software/anaconda3/envs/at_env/lib/python3.9/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /opt/lintula/worktmp/software/anaconda3/envs/at_env/lib/python3.9/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hsdadi/PycharmProjects/gpuRIR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hsdadi/PycharmProjects/gpuRIR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/lintula/worktmp/software/anaconda3/envs/at_env/lib/python3.9/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/lintula/worktmp/software/anaconda3/envs/at_env/lib/python3.9/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hsdadi/PycharmProjects/gpuRIR/CMakeFiles /home/hsdadi/PycharmProjects/gpuRIR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hsdadi/PycharmProjects/gpuRIR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpuRIRcu

# Build rule for target.
gpuRIRcu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpuRIRcu
.PHONY : gpuRIRcu

# fast build rule for target.
gpuRIRcu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIRcu.dir/build.make CMakeFiles/gpuRIRcu.dir/build
.PHONY : gpuRIRcu/fast

#=============================================================================
# Target rules for targets named gpuRIR_bind

# Build rule for target.
gpuRIR_bind: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpuRIR_bind
.PHONY : gpuRIR_bind

# fast build rule for target.
gpuRIR_bind/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIR_bind.dir/build.make CMakeFiles/gpuRIR_bind.dir/build
.PHONY : gpuRIR_bind/fast

src/gpuRIR_cuda.o: src/gpuRIR_cuda.cu.o
.PHONY : src/gpuRIR_cuda.o

# target to build an object file
src/gpuRIR_cuda.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIRcu.dir/build.make CMakeFiles/gpuRIRcu.dir/src/gpuRIR_cuda.cu.o
.PHONY : src/gpuRIR_cuda.cu.o

src/gpuRIR_cuda.i: src/gpuRIR_cuda.cu.i
.PHONY : src/gpuRIR_cuda.i

# target to preprocess a source file
src/gpuRIR_cuda.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIRcu.dir/build.make CMakeFiles/gpuRIRcu.dir/src/gpuRIR_cuda.cu.i
.PHONY : src/gpuRIR_cuda.cu.i

src/gpuRIR_cuda.s: src/gpuRIR_cuda.cu.s
.PHONY : src/gpuRIR_cuda.s

# target to generate assembly for a file
src/gpuRIR_cuda.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIRcu.dir/build.make CMakeFiles/gpuRIRcu.dir/src/gpuRIR_cuda.cu.s
.PHONY : src/gpuRIR_cuda.cu.s

src/python_bind.o: src/python_bind.cpp.o
.PHONY : src/python_bind.o

# target to build an object file
src/python_bind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIR_bind.dir/build.make CMakeFiles/gpuRIR_bind.dir/src/python_bind.cpp.o
.PHONY : src/python_bind.cpp.o

src/python_bind.i: src/python_bind.cpp.i
.PHONY : src/python_bind.i

# target to preprocess a source file
src/python_bind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIR_bind.dir/build.make CMakeFiles/gpuRIR_bind.dir/src/python_bind.cpp.i
.PHONY : src/python_bind.cpp.i

src/python_bind.s: src/python_bind.cpp.s
.PHONY : src/python_bind.s

# target to generate assembly for a file
src/python_bind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpuRIR_bind.dir/build.make CMakeFiles/gpuRIR_bind.dir/src/python_bind.cpp.s
.PHONY : src/python_bind.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gpuRIR_bind"
	@echo "... gpuRIRcu"
	@echo "... src/gpuRIR_cuda.o"
	@echo "... src/gpuRIR_cuda.i"
	@echo "... src/gpuRIR_cuda.s"
	@echo "... src/python_bind.o"
	@echo "... src/python_bind.i"
	@echo "... src/python_bind.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

